techpack: audio: Bump wcd_cpe state buffer
This silences the following compilation warning:

../techpack/audio/asoc/codecs/wcd_cpe_core.c:1981:2: error: 'snprintf' size argument is too large; destination buffer has size 11, but size argument is 13 [-Werror,-Wfortify-source]
        snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +
        ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
(cherry picked from commit 30ac6d9a20026bf76f48958de8599ea680238c6d)