wireguard: Fix redefinition error
In file included from <built-in>:2:
./../net/wireguard/compat/compat.h:827:20: error: redefinition of 'skb_mark_not_on_list'
static inline void skb_mark_not_on_list(struct sk_buff *skb)
                   ^
../include/linux/skbuff.h:1344:20: note: previous definition is here
static inline void skb_mark_not_on_list(struct sk_buff *skb)
                   ^
  CC      net/netfilter/xt_TEE.o
  CC      net/netfilter/xt_TRACE.o
  CC      net/netfilter/xt_IDLETIMER.o
1 error generated.
make[3]: *** [../scripts/Makefile.build:361: net/wireguard/main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      net/sched/em_meta.o
  AR      net/unix/unix.o
In file included from <built-in>:2:
./../net/wireguard/compat/compat.h:827:20: error: redefinition of 'skb_mark_not_on_list'
static inline void skb_mark_not_on_list(struct sk_buff *skb)
                   ^
../include/linux/skbuff.h:1344:20: note: previous definition is here
static inline void skb_mark_not_on_list(struct sk_buff *skb)

(cherry picked from commit 5bba7ca7ec2e3b336c3a8ae584b90ae5eac0a898)